version: "3.7"

services:
  apptest:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "tail -f /dev/null"
    depends_on:
      - postgrestest
    env_file:
      - .env.test

  postgrestest:
    image: postgres:latest
    env_file:
      - .env.test
    ports:
      - 5432:5432